apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gogcptest
  namespace: argocd
spec:
  project: gogcptest-project
  source:
    repoURL: https://github.com/amiroveisi/go_gcp_sample
    targetRevision: HEAD
    path: helm-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true