apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gogcptest-project
  namespace: argocd
spec:
  sourceRepos:
  - 'https://github.com/amiroveisi/go_gcp_sample'
  destinations:
  - namespace: default
    server: https://kubernetes.default.svc
  - namespace: staging
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: ''
    kind: Service
  - group: apps
    kind: Deployment
  - group: networking.k8s.io
    kind: Ingress